version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: db
  bot:
    build: .
    image: bot:latest
    ports:
      - 8000:80
    volumes:
      - '.:/src'
    depends_on:
      - db
    env_file:
      - .env